export const ActivityAction = {

    /// AUTH
    USER_REGISTER: 'USER_REGISTER',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD',
    USER_FORGOT_PASSWORD: 'USER_FORGOT_PASSWORD',
    USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',

    /// USER / PROFILE
    PROFILE_UPDATED: 'PROFILE_UPDATED',
    USER_STATUS_UPDATED: 'USER_STATUS_UPDATED',
    USER_ROLE_UPDATED: 'USER_ROLE_UPDATED',

    /// PRODUCT
    PRODUCT_VIEWED: 'PRODUCT_VIEWED',
    PRODUCT_CREATED: 'PRODUCT_CREATED',
    PRODUCT_UPDATED: 'PRODUCT_UPDATED',
    PRODUCT_DELETED: 'PRODUCT_DELETED',
    PRODUCT_RESTORED: 'PRODUCT_RESTORED',
    PRODUCT_TOGGLED: 'PRODUCT_TOGGLED',

    /// PRODUCT VARIANT
    VARIANT_CREATED: 'VARIANT_CREATED',
    VARIANT_UPDATED: 'VARIANT_UPDATED',
    VARIANT_TOGGLED: 'VARIANT_TOGGLED',

    /// PRODUCT ASSET
    ASSET_UPLOADED: 'ASSET_UPLOADED',
    ASSET_DELETED: 'ASSET_DELETED',
    ASSET_SET_PRIMARY: 'ASSET_SET_PRIMARY',

    /// BRAND
    BRAND_CREATED: 'BRAND_CREATED',
    BRAND_UPDATED: 'BRAND_UPDATED',
    BRAND_TOGGLED: 'BRAND_TOGGLED',
    BRAND_DELETED: 'BRAND_DELETED',

    /// CATEGORY
    CATEGORY_CREATED: 'CATEGORY_CREATED',
    CATEGORY_UPDATED: 'CATEGORY_UPDATED',
    CATEGORY_DELETED: 'CATEGORY_DELETED',

    /// CART
    CART_ITEM_ADDED: 'CART_ITEM_ADDED',
    CART_ITEM_UPDATED: 'CART_ITEM_UPDATED',
    CART_ITEM_REMOVED: 'CART_ITEM_REMOVED',
    CART_CLEARED: 'CART_CLEARED',
    CART_SYNCED: 'CART_SYNCED',

    /// WISHLIST
    WISHLIST_ADDED: 'WISHLIST_ADDED',
    WISHLIST_REMOVED: 'WISHLIST_REMOVED',

    /// ORDER
    ORDER_PLACED: 'ORDER_PLACED',
    ORDER_CANCELLED: 'ORDER_CANCELLED',
    ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
    ORDER_REORDERED: 'ORDER_REORDERED',

    /// PAYMENT
    PAYMENT_INITIATED: 'PAYMENT_INITIATED',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_FAILED: 'PAYMENT_FAILED',

} as const;

export type ActivityActionType = typeof ActivityAction[keyof typeof ActivityAction];